# Generated by Django 4.0.2 on 2022-02-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0003_dealers_form_drivers_form_delete_dealers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealers_form',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
